name: 'Cache Dependencies'
description: 'Set up Node.js, cache node_modules, and install dependencies'
inputs:
  NPM_TOKEN:
    description: 'NPM token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: '⚙️ Use Node.js'
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        check-latest: true
        registry-url: https://npm.pkg.github.com/
        scope: '@eviden-parallel'

    - name: 'Cache dependencies'
      uses: actions/cache@v3
      id: cache-deps
      with:
        path: node_modules
        key: node-deps-${{ hashFiles('**/package-lock.json') }}

    - name: '⛓️ Install dependencies'
      if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
        HUSKY: 0
      run: npm ci --no-optional --no-audit --prefer-offline --progress=false
      shell: bash # this is required to use the run keyword. shell specifies which shell to use to run the command.